### ISSUE TITLE
CommonJS build

### ISSUE THREAD

**Issue by ierehon1905** [yandex-cloud/axios-wrapper#8]
Hello, I encounter some problems using jest with this library because it uses esm as main entry file for this package.

Is it possible to make both esm and cjs build ? Or how can I use this with jest?

**Comment by tsufiev** [comment]
@ierehon1905 Will https://github.com/yandex-cloud/axios-wrapper/pull/9 be enough for your needs?

**Comment by ierehon1905** [comment]
@tsufiev seems like it, honestly idk till I try

**Comment by ierehon1905** [comment]
Thank you, the issue is solved in #9
